name: my_finance_demo
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.15.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  pie_chart: 
    # ^5.1.0
    # path: C:/Users/adnan/pie_chart
    # I've implemented the half pie feature, however,
    # as it is not merged yet, I'll be using my own fork
    # temporarily.
    git: 
      url: https://www.github.com/adnanjpg/pie_chart.git
      ref: totalDegrees
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true
  fonts:
    - family: Buntype
      fonts:
        - asset: assets/fonts/Buntype.otf